services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm run start:dev
    environment:
      MONGO_URI: mongodb://mongodb:27017/ConsultorioNutricionista
    depends_on:
      - mongodb

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "28017:27017"
    volumes:
      - mongodb_data:/data/db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend

volumes:
  mongodb_data:
  node_modules:
