services:
    backend:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
            - node_modules:/usr/src/app/node_modules
        command: npm run start:dev
        environment:
            MONGO_URI: mongodb://mongodb:27017/ConsultorioNutricionista
        depends_on:
            - mongodb

    mongodb:
        image: mongo:6.0
        container_name: mongodb
        ports:
            - '28017:27017'
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data:
    node_modules:
