services:
    backend:
        build: .
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        command: npm run start:dev # Roda o servidor no modo desenvolvimento
        environment:
            MONGO_URI: mongodb://mongodb:27017/ConsultorioNutricionista # Variável de ambiente para conexão com o MongoDB
        depends_on:
            - mongodb

    mongodb:
        image: mongo:6.0
        container_name: mongodb
        ports:
            - '28017:27017' # Porta do MongoDB
        volumes:
            - mongodb_data:/data/db

volumes:
    mongodb_data: # Volume para persistência do banco
